name: $(BuildDefinitionName).$(Build.SourceBranchName).$(Rev:.r)

trigger: none

pr:
- master

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Janus:
          stage.name: 'janus'
          container.name: 'ivadim/fruitnanny-janus'
        GStreamer:
          stage.name: 'gstreamer'
          container.name: 'ivadim/fruitnanny-gstreamer'
        Fruitnanny:
          stage.name: 'fruitnanny'
          container.name: 'ivadim/fruitnanny-app'
      maxParallel: 3

    steps:
    - script: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce
        docker --version
      displayName: 'Update docker'
    - script: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build . -f docker/$(stage.name)/Dockerfile -t $(container.name) --platform arm
        docker images
        docker inspect $(container.name)
      displayName: 'Build $(stage.name) Container'
