version: '3'
services:
  notification-temp:
    build:
      context: .
      dockerfile: notification/Dockerfile
    restart: always
    network_mode: "host"
    privileged: true
    depends_on:
      - nginx
      - janus
      - fruitnanny
    #command: /bin/bash
    #tty: true
    command: python3 /opt/notification/temperature.py

  notification-motion:
    build:
      context: .
      dockerfile: notification/Dockerfile
    restart: always
    network_mode: "host"
    privileged: true
    depends_on:
      - nginx
      - janus
      - fruitnanny
    #command: /bin/bash
    #tty: true
    command: python3 /opt/notification/motion.py
